from enum import Enum

from django.db import models
from django.utils import timezone


class Session(models.Model):

    class State(Enum):
        OPENED = "OPENED"
        VERIFIED = "VERIFIED"
        CLOSED = "CLOSED"

        @classmethod
        def choices(cls):
            return tuple((k.name, k.value) for k in cls)

    # mandatory fields
    name = models.TextField(max_length=200)
    code = models.CharField(max_length=40, unique=True)
    location_id = models.IntegerField()

    # optional fields
    state = models.CharField(max_length=255, choices=State.choices(), default=State.OPENED)

    # autogenerated fields
    timestamp = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ["name", "location_id"]
        indexes = [
            models.Index(fields=["location_id"]),
            models.Index(fields=["state"]),
        ]
