# Generated by Django 2.2.6 on 2019-10-29 10:06

from django.db import migrations, models
import django.utils.timezone
import sessions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('location_id', models.IntegerField()),
                ('state', models.CharField(choices=[('OPENED', 'OPENED'), ('VERIFIED', 'VERIFIED'), ('CLOSED', 'CLOSED')], default=sessions.models.SessionState('OPENED'), max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['location_id'], name='sessions_se_locatio_bae49a_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['state'], name='sessions_se_state_86a38f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('name', 'location_id')},
        ),
    ]
