# Generated by Django 2.2.6 on 2020-01-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
